# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#Build settings
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
title: Volcanic Minds
logo: "/assets/images/logo-dark.png"
author:
  name: Volcanic Minds
  email: info@volcanicminds.com
color_scheme: volcanicminds
favicon_ico: "/assets/images/favicon.ico"
markdown_ext: "md"
footer_content: "Volcanic Minds S.r.l. a socio unico - Corso Vinzaglio 24, 10121 Torino (TO) - P.IVA 12754330012"
# minima:
#   social_links:
#     - {
#         platform: linkedin,
#         user_url: "https://www.linkedin.com/company/volcanic-minds",
#       }
#     - {
#         platform: instagram,
#         user_url: "https://www.instagram.com/volcanic_minds/",
#       }
#   header_pages:
#     - company.html
#     - company-growth.html
#     - how-we-work.html
#     - personal-growth.html
#     - contact-us.html
#   show_excerpts: false

description: >- # this means to ignore newlines until "baseurl:"
  This is the Volcanic Minds Business Playbook, which describes the guidelines and values
  on which the company is based.
url: "https://playbook.volcanicminds.com"
github_username: volcanicminds
repository: volcanicminds/volcanic-minds-playbook

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Site search
search_enabled: true
search:
  button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# External navigation links
nav_external_links:
  - title: Our website
    url: https://volcanicminds.com

# Footer last edited timestamp
last_edit_timestamp: false # default date in footer is disabled, redefined on footer_customr.html
last_edit_time_format: "%e %B %Y"
